### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by 3IWOH** [tflanagan/node-quickbase#1]
I am unable to connect to quickbase with the following error:

/home/test/node/node_modules/quickbase/QuickBase.js:281
                this.queries[query].response = {status: status, results: results};
                            ^
TypeError: Cannot read property '0' of undefined
    at ClientRequest.quickbase._return (/home/hoakes/E2E/node/node_modules/quickbase/QuickBase.js:281:15)
    at ClientRequest.<anonymous> (/home/hoakes/E2E/node/node_modules/quickbase/QuickBase.js:264:17)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at Socket.onerror (tls.js:1445:17)
    at Socket.EventEmitter.emit (events.js:117:20)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

I have verified I can access the qb url via cURL. I am behind an http proxy, but I have the proxy set in my environment variables.

any help would be appreciated.

**Comment by tflanagan** [comment]
closing due to inactivity.

ps: look at v3, targets the new json based api with proxy support
